### ISSUE TITLE
Module Resolution Error: Missing File Extensions in Import Statements

### ISSUE THREAD

**Issue by digitAI-4N6** [theKashey/react-focus-lock#305] opened 2024-04-21 21:21 UTC
Description:
When attempting to build a React project using npm install, the following build errors are encountered:

ERROR in ./node_modules/react-focus-lock/dist/es2015/index.js 1:0-38
Module not found: Error: Can't resolve './Combination' in '/path_to_project/node_modules/react-focus-lock/dist/es2015'
Did you mean 'Combination.js'?
BREAKING CHANGE: The request './Combination' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e.g., a module with JavaScript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/react-focus-lock/dist/es2015/index.js 2:0-21
Module not found: Error: Can't resolve './UI' in '/path_to_project/node_modules/react-focus-lock/dist/es2015'
Did you mean 'UI.js'?
BREAKING CHANGE: The request './UI' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e.g., a module with JavaScript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

Steps to reproduce:
Create new react app
Run npm install.

**Comment by theKashey** [comment] 2024-04-21 23:49
Duplicate of #301 
Just downgrade to 2.11.3

**Closed by theKashey** 2024-04-21 23:49 UTC

**Comment by digitAI-4N6** [comment] 2024-04-22 01:15
Oh, I didn't find that. Thank you.
