### ISSUE TITLE
Tabindex issue

### ISSUE THREAD

**Issue by bikasv** [theKashey/react-focus-lock#32] opened 2018-06-15 08:55 UTC
Hi,
Accessibility tools generally freaks when tabindex is greater than 0 and it seems this library is using tabindex 1 in place.
I'm not sure how important is that to have that implementation, but is it possible to run with tabindex 0 only?

**Comment by theKashey** [comment] 2018-06-16 02:59
And could you elaborate more about _Accessibility tools_, may be it is better to add a new option, forcing guards not to use positive tabindexes, as long they are needed cos you might have them inside.

**Comment by theKashey** [comment] 2018-06-17 09:58
Good luck then!

**Comment by crshmk** [comment] 2021-11-29 15:24
I suggest reopening this. Our accessibility team also takes serious issue with the tabIndex of 1.

I believe the issue is [here](https://github.com/theKashey/react-focus-lock/blob/4ef6569cd8be56b592a08ad951e84af4d0beaad6/src/Lock.js#L139). Is there any reason why this tabIndex cannot be 0 rather than 1? Everything seems to work correctly for me when I set it 0.

**Comment by theKashey** [comment] 2021-11-29 22:39
`guard-nearest` is just an extra precaution, which might be helpful __if__ if you positive indexes in other places.
If you don't - then it's completely useless.

Thank for raising this question, it might be a good time to reconsider this moment

Related:
- https://github.com/theKashey/vue-focus-lock/issues/23

**Comment by crshmk** [comment] 2021-11-30 23:05
https://github.com/theKashey/react-focus-lock/pull/182

**Comment by crshmk** [comment] 2021-12-03 14:26
@theKashey in the PR, I was just suggesting a couple of api options to get this rolling. If you have a way you'd prefer to do this, feel free to let me know and I'll update as you like.

**Comment by theKashey** [comment] 2022-02-13 03:50
Not yet released....

**Comment by theKashey** [comment] 2022-02-14 03:15
Update released as version `2.8.0`

**Closed by theKashey** 2022-02-14 03:15 UTC
Labels: WIP
