### ISSUE TITLE
Problem with focusing element in modals

### ISSUE THREAD

**Issue by One041** [theKashey/react-focus-lock#340] opened 2024-10-26 12:35 UTC
Hello. I tried to use the focus lock inside modals and stuck with a problem to focus element. Right now you need press the tab key twice to focus the first element in the modal. **autoFocus** was set to **false** since I don't want to focus any element until press the tab key. Is it possible to focus an element in modals with single tab?

#### Demo:
https://ping-roan.vercel.app/

Just click the "Open modal" button and try to focus any element.

Source code: https://github.com/One041/ping

**Comment by AlekseyManetov** [comment] 2024-11-04 17:04
We encountered the same issue after updating from version 2.9.2 to 2.13.2. We are experiencing even more unusual behavior: once a modal with FocusLock is mounted, the user has to press the Tab key approximately the same number of times as there are active elements on the page following the modal toggle button.

I've created a CodeSandbox to demonstrate this issue: https://codesandbox.io/p/sandbox/kdcn3q

@theKashey Could you please take a look at this case? It seems quite critical.

**Comment by AlekseyManetov** [comment] 2024-12-09 15:11
As a temporary fix we add autofocus first active element on modal open. It's a temporary fix, because of bug in react-focus-lock lib(https://github.com/theKashey/react-focus-lock/issues/340). Ideally focus should move to the first active element only after 'Tab' key was pressed, we will come back to this solution when bug will be fixed.

**Closed** 2024-12-15 03:19 UTC

**Comment by theKashey** [comment] 2024-12-15 03:22
Sorry for a little late reaction. Indeed that was a bug introduced in the last release, hopefully affecting only `autoFocus:false` behavior.

I was not able to replicate it via unit tests, but was able to clearly reproduce in storybook following example provided by @AlekseyManetov, and then get it fixed. 

`2.13.5` should fix your problem.
